image: netroby/alpine-rsync

pages:
  stage: deploy
  script:
    - echo 'Deploying to Gitlab Pages.'
    - rsync -av --progress . public/ --exclude public --exclude .git
    - rm public/.gitignore && rm public/.gitlab-ci.yml
    - rm public/CNAME && rm public/README.md && rm package-lock.json && rm package.json
  artifacts:
    paths:
      - public
  only:
    - master
